# Generated by Django 3.1.7 on 2021-03-24 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Биография должна быть не короче 10 символов')], verbose_name='Описание'),
        ),
    ]
