# Generated by Django 3.1.7 on 2021-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_advuser_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?'),
        ),
    ]
