# Generated by Django 3.1.7 on 2021-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210320_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
